version: "3.6"

services:
  nginx:
    image: easybar/nginx:dev
    depends_on:
      - app
    ports:
      - "8080:80"
    environment:
      - DOCROOT=/srv/public
    volumes:
      - .:/srv
  app:
    image: easybar/php:7.2.9-dev
    depends_on:
      - db
    volumes:
      - .:/srv

  db:
    image: mariadb:10.2.10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=allan_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      -   '3306:3306'
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=brade
volumes:
  db-data: {}